# Utilisation de l'image Python basée sur Alpine
FROM node:18-alpine

# Définit le répertoire de travail dans le conteneur
WORKDIR /app

# Copie les fichiers nécessaires
COPY package.json ./
COPY package-lock.json ./

RUN npm install

# Copie le reste du code
COPY . .

# Expose le port de l’API Next.js
EXPOSE 3000

# Commande pour démarrer Next.js en mode développement
CMD ["npm", "run", "dev"]
