services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - db_data:/app/bd  # Monte le volume db_data dans le conteneur à /app/bd
    command: gunicorn wsgi:app --bind 0.0.0.0:5000
    networks:
      - frontend-backend-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - frontend-backend-network

networks:
  frontend-backend-network:
    driver: bridge

volumes:
  db_data:  # Création du volume db_data
    # Optionnel : tu peux ajouter des options ici, par exemple, si tu veux spécifier un driver ou un chemin
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /path/to/your/local/dir
    #   o: bind
