import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

import UserMenu from "./UserMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 return (
   <html lang="fr" data-theme="cupcake">
     <body
       className={`${geistSans.variable} ${geistMono.variable} antialiased p-0 lg:px-8 relative`}
     >
       <header className="banner">
         <Link href="/" className="grid grid-cols-6 items-center gap-2 justify-items-center">
           <Image
             className="block h-auto"
             src="/img/pussay_logo.png"
             alt="Logo Pussay"
             width={223}
             height={349}
           />
           <Image
             className="block col-span-4 rounded"
             src="/img/bandeau.jpg"
             alt="Bandeau"
             width={914}
             height={275}
           />
           <Image
             className="block w-auto"
             src="/img/territoire-engage-nature.png"
             alt="Label Territoire Engagé Nature"
             width={223}
             height={254}
           />
         </Link>
       </header>

       <nav className="navbar bg-[var(--color-1)] col-span-6 flex items-center gap-2 rounded h-10 sticky top-[0.5rem] z-50">
         <Link href="/" className="w-auto h-full aspect-square block p-2">
           <Image
             className="aspect-auto"
             src="/img/shell.png"
             alt="Accueil"
             width={40}
             height={40}
           />
         </Link>
         <div className="flex-1">
           <ul className="hidden menu lg:menu-horizontal px-1 text-white">
             <li>
               <Link href="/associations">ass</Link>
             </li>
             <li>
               <details>
                 <summary>Parent</summary>
                 <ul className="bg-base-100 rounded-t-none p-2 text-black">
                   <li>
                     <Link href="#">lien1</Link>
                   </li>
                   <li>
                     <Link href="#">lien2</Link>
                   </li>
                 </ul>
               </details>
             </li>
           </ul>
         </div>
         <UserMenu />
       </nav>
       {children}
       {/* <footer className="footer bg-[var(--color-1)] text-white p-10 rounded-t mt-[1em]">
         <nav>
           <h6 className="footer-title">
             <Link href="/login">espace privé</Link>
           </h6>
         </nav>
       </footer> */}
       <footer className="footer bg-[var(--color-1)] text-white p-10 rounded-t mt-[1em]">
         <nav>
           <h6 className="footer-title">Services</h6>
           <Link href="#" className="link link-hover">Branding</Link>
           <Link href="#" className="link link-hover">Design</Link>
           <Link href="#" className="link link-hover">Marketing</Link>
           <Link href="#" className="link link-hover">Advertisement</Link>
         </nav>
         <nav>
           <h6 className="footer-title">Company</h6>
           <Link href="#" className="link link-hover">About us</Link>
           <Link href="#" className="link link-hover">Contact</Link>
           <Link href="#" className="link link-hover">Jobs</Link>
           <Link href="#" className="link link-hover">Press kit</Link>
         </nav>
         <nav>
           <h6 className="footer-title">Legal</h6>
           <Link href="#" className="link link-hover">Terms of use</Link>
           <Link href="#" className="link link-hover">Privacy policy</Link>
           <Link href="#" className="link link-hover">Cookie policy</Link>
         </nav>
         <nav>
           <h6 className="footer-title">
             <Link href="/login">espace privé</Link>
           </h6>
         </nav>
       </footer>
       <footer className="footer bg-[var(--color-1)] text-white border-base-300 border-t px-10 py-4 justify-items-center lg:justify-items-start">
         <aside className="grid-flow-col items-center">
           <Link href="/" className="w-14 h-full aspect-square block p-2">
             <Image width={56} height={64.5} className="aspect-auto" src="/img/shell.png" alt="" />
           </Link>
         </aside>
         <nav className="md:place-self-center md:justify-self-end">
           <div className="grid grid-flow-col gap-4">
             <a>
               <svg
                 xmlns="http://www.w3.org/2000/svg"
                 width="24"
                 height="24"
                 viewBox="0 0 24 24"
                 className="fill-current"
               >
                 <path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path>
               </svg>
             </a>
             <a>
               <svg
                 xmlns="http://www.w3.org/2000/svg"
                 width="24"
                 height="24"
                 viewBox="0 0 24 24"
                 className="fill-current"
               >
                 <path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path>
               </svg>
             </a>
             <a>
               <svg
                 xmlns="http://www.w3.org/2000/svg"
                 width="24"
                 height="24"
                 viewBox="0 0 24 24"
                 className="fill-current"
               >
                 <path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path>
               </svg>
             </a>
           </div>
         </nav>
       </footer>
     </body>
   </html>
 );
}
