name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Clear previous build files on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Ajustement des permissions..."
            sudo chown -R ${{ secrets.USERNAME }}:${{ secrets.USERNAME }} /home/deploy-cnam_projet/cnam_projet
            sudo chmod -R u+rwX /home/deploy-cnam_projet/cnam_projet
            echo "Suppression du dossier cnam_projet..."
            sudo rm -rf /home/deploy-cnam_projet/cnam_projet
            echo "Création du répertoire cnam_projet..."
            mkdir /home/deploy-cnam_projet/cnam_projet
            echo "Répertoire créé."

      - name: Copy Build to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "."
          target: "/home/deploy-cnam_projet/cnam_projet"
          strip_components: 1
          overwrite: true  # Assurer que les fichiers existants sont écrasés

      - name: Deploy containers on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Vérification de Docker..."
            if ! systemctl is-active --quiet docker; then
              echo "Docker n'est pas actif. Tentative de démarrage..."
              sudo systemctl start docker
            fi
            cd /home/deploy-cnam_projet/cnam_projet

            echo "Nettoyage des anciens conteneurs et images..."
            docker-compose down
            docker system prune -f
            
            echo "Chargement des variables d'environnement..."
            echo "${{ secrets.ENV }}" > /home/deploy-cnam_projet/cnam_projet/backend/.env
            echo "${{ secrets.ENV }}" > /home/deploy-cnam_projet/cnam_projet/frontend/.env
            
            echo "Lancement des nouveaux conteneurs..."
            docker-compose up -d --build

            echo "Déploiement terminé avec succès !"
